In [1]:
import yfinance as yf

data = yf.Ticker("MSFT")
data.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The Productivity and Business Processes segment offers Microsoft 365 commercial, enterprise mobility + security, windows commercial, power BI, exchange, sharepoint, Microsoft teams, security and compliance, and copilot; Microsoft 365 commercial products, such as Windows commercial on-premises and office licensed services; Microsoft 365 consumer products and cloud services, including Microsoft 365 consumer subscriptions, office licensed on-premises, and other consumer services; LinkedIn; dynamics products and cloud services, such as dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services comprising Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; server products, including SQL and windows server, visual studio and system center related client access licenses, and other on-premises offerings; enterprise and partner services, such as enterprise support and nuance professional services, industry solutions, Microsoft partner network, and learning experience. The Personal Computing segment provides windows and devices, such as Windows OEM licensing and devices and surface and PC accessories; gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox game pass, subscriptions, and cloud gaming, advertising, and other cloud services; search and news advertising services that includes Bing and Copilot, Microsoft News and Edge, and third-party affiliates. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 4,
 'governanceEpochDate': 1777593600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 409.43002,
 'open': 414.41,
 'dayLow': 412.92,
 'dayHigh': 428.16,
 'regularMarketPreviousClose': 409.43002,
 'regularMarketOpen': 414.41,
 'regularMarketDayLow': 412.92,
 'regularMarketDayHigh': 428.16,
 'dividendRate': 3.64,
 'dividendYield': 0.86,
 'exDividendDate': 1779321600,
 'payoutRatio': 0.20729999,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.093,
 'trailingPE': 25.129244,
 'forwardPE': 21.78098,
 'volume': 50771160,
 'regularMarketVolume': 50771160,
 'averageVolume': 34354716,
 'averageVolume10days': 33368700,
 'averageDailyVolume10Day': 33368700,
 'bid': 420.79,
 'ask': 422.04,
 'bidSize': 2,
 'askSize': 2,
 'marketCap': 3134205460480,
 'nonDilutedMarketCap': 3083691814324,
 'fiftyTwoWeekLow': 356.28,
 'fiftyTwoWeekHigh': 555.45,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 9.847538,
 'fiftyDayAverage': 399.0648,
 'twoHundredDayAverage': 463.13254,
 'trailingAnnualDividendRate': 3.56,
 'trailingAnnualDividendYield': 0.008695015,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3181409206272,
 'profitMargins': 0.39341998,
 'floatShares': 7417440621,
 'sharesOutstanding': 7428434704,
 'sharesShort': 79107882,
 'sharesShortPriorMonth': 80991357,
 'sharesShortPreviousMonthDate': 1774915200,
 'dateShortInterest': 1777507200,
 'sharesPercentSharesOut': 0.0106,
 'heldPercentInsiders': 0.0008,
 'heldPercentInstitutions': 0.75657,
 'shortRatio': 2.26,
 'shortPercentOfFloat': 0.0107,
 'impliedSharesOutstanding': 7428434704,
 'bookValue': 55.777,
 'priceToBook': 7.5644083,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1774915200,
 'earningsQuarterlyGrowth': 0.231,
 'netIncomeToCommon': 125215997952,
 'trailingEps': 16.79,
 'forwardEps': 19.37103,
 'pegRatio': 1.3,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 9.996,
 'enterpriseToEbitda': 17.247,
 '52WeekChange': -0.08052391,
 'SandP52WeekChange': 0.24228656,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1771459200,
 'quoteType': 'EQUITY',
 'currentPrice': 421.92,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 560.6302,
 'targetMedianPrice': 557.5,
 'recommendationMean': 1.30909,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 54,
 'totalCash': 78227996672,
 'totalCashPerShare': 10.531,
 'ebitda': 184457003008,
 'totalDebt': 125431996416,
 'quickRatio': 1.142,
 'currentRatio': 1.283,
 'totalRevenue': 318272995328,
 'debtToEquity': 30.271,
 'revenuePerShare': 42.836,
 'returnOnAssets': 0.14814,
 'returnOnEquity': 0.34013999,
 'grossProfits': 217409994752,
 'freeCashflow': 37011251200,
 'operatingCashflow': 170141007872,
 'earningsGrowth': 0.234,
 'revenueGrowth': 0.183,
 'grossMargins': 0.68309,
 'ebitdaMargins': 0.57956004,
 'operatingMargins': 0.46326,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'fiftyDayAverageChange': 22.855225,
 'fiftyDayAverageChangePercent': 0.057271965,
 'twoHundredDayAverageChange': -41.212524,
 'twoHundredDayAverageChangePercent': -0.08898646,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'preMarketChangePercent': -0.50247097,
 'preMarketPrice': 419.8,
 'regularMarketChange': 12.48999,
 'regularMarketDayRange': '412.92 - 428.16',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 34354716,
 'fiftyTwoWeekLowChange': 65.640015,
 'fiftyTwoWeekLowChangePercent': 0.18423715,
 'fiftyTwoWeekRange': '356.28 - 555.45',
 'fiftyTwoWeekHighChange': -133.53,
 'fiftyTwoWeekHighChangePercent': -0.24039967,
 'fiftyTwoWeekChangePercent': -8.052391,
 'dividendDate': 1781136000,
 'earningsTimestamp': 1777492800,
 'earningsTimestampStart': 1785355200,
 'earningsTimestampEnd': 1785355200,
 'earningsCallTimestampStart': 1777498200,
 'earningsCallTimestampEnd': 1777498200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 16.79,
 'epsForward': 19.37103,
 'epsCurrentYear': 16.84516,
 'priceEpsCurrentYear': 25.046959,
 'corporateActions': [{'header': 'Dividend',
   'message': 'MSFT announced a cash dividend of $0.91 with an ex-date of May. 21, 2026',
   'meta': {'eventType': 'DIVIDEND',
    'dateEpochMs': 1779336000000,
    'amount': '0.91'}}],
 'preMarketTime': 1779092180,
 'regularMarketTime': 1778875201,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 3.0505798,
 'regularMarketPrice': 421.92,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'preMarketChange': -2.1200256,
 'marketState': 'PRE',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.2863}

In [1]:
import yfinance as yf

data = yf.Ticker("VTI")
data.info

{'phone': '800-523-1036',
 'longBusinessSummary': 'The fund manager employs an indexing investment approach designed to track the performance of the CRSP U.S. Total Market Index (the “Target Index”), which represents 100% of the investable U.S. stock market, as determined by the index provider. Under normal circumstances, the fund invests at least 80% of its net assets, plus the amount of any borrowings for investment purposes, in the stocks that make up the target index.',
 'companyOfficers': [],
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 362.36,
 'open': 360.65,
 'dayLow': 358.802,
 'dayHigh': 361.96,
 'regularMarketPreviousClose': 362.36,
 'regularMarketOpen': 360.65,
 'regularMarketDayLow': 358.802,
 'regularMarketDayHigh': 361.96,
 'trailingPE': 26.747149,
 'volume': 3136670,
 'regularMarketVolume': 3136670,
 'averageVolume': 4764662,
 'averageVolume10days': 3328590,
 'averageDailyVolume10Day': 3328590,
 'bid': 0.0,
 'ask': 0.0,
 'bidSize': 120,
 'askSize': 400,
 'yield': 0.0106,
 'totalAssets': 2202624327680,
 'fiftyTwoWeekLow': 283.0,
 'fiftyTwoWeekHigh': 368.25,
 'allTimeHigh': 368.25,
 'allTimeLow': 29.76,
 'fiftyDayAverage': 341.3758,
 'twoHundredDayAverage': 333.74216,
 'trailingAnnualDividendRate': 2.802,
 'trailingAnnualDividendYield': 0.007732642,
 'navPrice': 362.33,
 'currency': 'USD',
 'tradeable': False,
 'category': 'Large Blend',
 'ytdReturn': 5.97418,
 'beta3Year': 1.03,
 'fundFamily': 'Vanguard',
 'fundInceptionDate': 974073600,
 'legalType': 'Exchange Traded Fund',
 'threeYearAverageReturn': 0.2192139,
 'fiveYearAverageReturn': 0.1274803,
 'quoteType': 'ETF',
 'symbol': 'VTI',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'ETF',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 992611800000,
 'postMarketChangePercent': -0.0027800272,
 'postMarketPrice': 360.05,
 'postMarketChange': -0.010009766,
 'regularMarketChange': -2.29999,
 'regularMarketDayRange': '358.802 - 361.96',
 'fullExchangeName': 'NYSEArca',
 'financialCurrency': 'USD',
 'averageDailyVolume3Month': 4764662,
 'fiftyTwoWeekLowChange': 77.06,
 'fiftyTwoWeekLowChangePercent': 0.27229682,
 'fiftyTwoWeekRange': '283.0 - 368.25',
 'fiftyTwoWeekHighChange': -8.190002,
 'fiftyTwoWeekHighChangePercent': -0.022240333,
 'fiftyTwoWeekChangePercent': 25.557064,
 'dividendYield': 1.06,
 'trailingThreeMonthReturns': 4.32494,
 'trailingThreeMonthNavReturns': 4.32494,
 'netAssets': 2202624330000.0,
 'epsTrailingTwelveMonths': 13.461622,
 'sharesOutstanding': 743262976,
 'bookValue': 139.506,
 'fiftyDayAverageChange': 18.684204,
 'fiftyDayAverageChangePercent': 0.05473207,
 'twoHundredDayAverageChange': 26.31784,
 'twoHundredDayAverageChangePercent': 0.0788568,
 'netExpenseRatio': 0.03,
 'priceToBook': 2.5809643,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'corporateActions': [],
 'postMarketTime': 1779235172,
 'regularMarketTime': 1779220800,
 'exchange': 'PCX',
 'messageBoardId': 'finmb_6184536',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -0.634725,
 'regularMarketPrice': 360.06,
 'marketState': 'PREPRE',
 'cryptoTradeable': False,
 'shortName': 'Vanguard Total Stock Market ETF',
 'longName': 'Vanguard Total Stock Market Index Fund ETF Shares',
 'trailingPegRatio': None}

In [2]:
data.calendar

{'Dividend Date': datetime.date(2026, 6, 11),
 'Ex-Dividend Date': datetime.date(2026, 5, 21),
 'Earnings Date': [datetime.date(2026, 7, 30)],
 'Earnings High': 4.89,
 'Earnings Low': 4.07,
 'Earnings Average': 4.24777,
 'Revenue High': 91239000000,
 'Revenue Low': 86900000000,
 'Revenue Average': 87610832320}

In [3]:
data.analyst_price_targets

{'current': 412.66,
 'high': 870.0,
 'low': 400.0,
 'mean': 561.5561,
 'median': 562.5}

In [4]:
data.quarterly_income_stmt

,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31
Tax Effect Of Unusual Items,281390000.0,65200000.0,187150000.0,495125.091979,69660000.0
Tax Rate For Calcs,0.19,0.2,0.19,0.165042,0.18
Normalized EBITDA,48804000000.0,57854000000.0,47075000000.0,44431000000.0,39318000000.0
Total Unusual Items,1481000000.0,326000000.0,985000000.0,3000000.0,387000000.0
Total Unusual Items Excluding Goodwill,1481000000.0,326000000.0,985000000.0,3000000.0,387000000.0
Net Income From Continuing Operation Net Minority Interest,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Reconciled Depreciation,10167000000.0,9198000000.0,13061000000.0,11203000000.0,7734000000.0
Reconciled Cost Of Revenue,26828000000.0,25978000000.0,24043000000.0,24014000000.0,21919000000.0
EBITDA,50285000000.0,58180000000.0,48060000000.0,44434000000.0,39705000000.0
EBIT,40118000000.0,48982000000.0,34999000000.0,33231000000.0,31971000000.0
Net Interest Income,-48000000.0,104000000.0,278000000.0,154000000.0,3000000.0
Interest Expense,778000000.0,736000000.0,698000000.0,615000000.0,594000000.0
Interest Income,730000000.0,840000000.0,976000000.0,769000000.0,597000000.0
Normalized Income,30578390000.0,38197200000.0,26949150000.0,27230495125.09198,25506660000.0
Net Income From Continuing And Discontinued Operation,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Total Expenses,44488000000.0,42998000000.0,39712000000.0,42118000000.0,38066000000.0
Total Operating Income As Reported,38398000000.0,38275000000.0,37961000000.0,34323000000.0,32000000000.0
Diluted Average Shares,7445000000.0,7460000000.0,7466000000.0,7461000000.0,7461000000.0
Basic Average Shares,7426000000.0,7431000000.0,7433000000.0,7432000000.0,7434000000.0
Diluted EPS,4.27,5.16,3.72,3.65,3.46
Basic EPS,4.28,5.18,3.73,3.66,3.47
Diluted NI Availto Com Stockholders,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Net Income Common Stockholders,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Net Income,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Net Income Including Noncontrolling Interests,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Net Income Continuous Operations,31778000000.0,38458000000.0,27747000000.0,27233000000.0,25824000000.0
Tax Provision,7562000000.0,9788000000.0,6554000000.0,5383000000.0,5553000000.0
Pretax Income,39340000000.0,48246000000.0,34301000000.0,32616000000.0,31377000000.0
Other Income Expense,990000000.0,9867000000.0,-3938000000.0,-1861000000.0,-626000000.0
Other Non Operating Income Expenses,-491000000.0,9541000000.0,-4923000000.0,-1864000000.0,-1013000000.0
Special Income Charges,-37000000.0,-59000000.0,-14000000.0,-45000000.0,-24000000.0
Write Off,37000000.0,59000000.0,14000000.0,45000000.0,24000000.0
Gain On Sale Of Security,1518000000.0,385000000.0,999000000.0,48000000.0,411000000.0
Net Non Operating Interest Income Expense,-48000000.0,104000000.0,278000000.0,154000000.0,3000000.0
Interest Expense Non Operating,778000000.0,736000000.0,698000000.0,615000000.0,594000000.0
Interest Income Non Operating,730000000.0,840000000.0,976000000.0,769000000.0,597000000.0
Operating Income,38398000000.0,38275000000.0,37961000000.0,34323000000.0,32000000000.0
Operating Expense,17660000000.0,17020000000.0,15669000000.0,18104000000.0,16147000000.0
Research And Development,8915000000.0,8504000000.0,8146000000.0,8829000000.0,8198000000.0
Selling General And Administration,8745000000.0,8516000000.0,7523000000.0,9275000000.0,7949000000.0
Selling And Marketing Expense,6814000000.0,6584000000.0,5717000000.0,7285000000.0,6212000000.0
General And Administrative Expense,1931000000.0,1932000000.0,1806000000.0,1990000000.0,1737000000.0
Other Gand A,1931000000.0,1932000000.0,1806000000.0,1990000000.0,1737000000.0
Gross Profit,56058000000.0,55295000000.0,53630000000.0,52427000000.0,48147000000.0
Cost Of Revenue,26828000000.0,25978000000.0,24043000000.0,24014000000.0,21919000000.0
Total Revenue,82886000000.0,81273000000.0,77673000000.0,76441000000.0,70066000000.0
Operating Revenue,82886000000.0,81273000000.0,77673000000.0,76441000000.0,70066000000.0

In [5]:
data.history(period="1mo")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-04-13 00:00:00-04:00,373.609985,384.540009,371.019989,384.369995,35745800,0.0,0.0
2026-04-14 00:00:00-04:00,387.920013,394.690002,386.519989,393.109985,37504500,0.0,0.0
2026-04-15 00:00:00-04:00,398.000000,414.369995,396.730011,411.220001,45063400,0.0,0.0
2026-04-16 00:00:00-04:00,419.859985,420.820007,412.140015,420.260010,41642400,0.0,0.0
2026-04-17 00:00:00-04:00,424.820007,431.579987,420.690002,422.790009,48568200,0.0,0.0
2026-04-20 00:00:00-04:00,421.149994,423.329987,416.299988,418.070007,27582200,0.0,0.0
2026-04-21 00:00:00-04:00,420.239990,427.179993,417.200012,424.160004,32048500,0.0,0.0
2026-04-22 00:00:00-04:00,426.190002,433.700012,423.670013,432.920013,29378200,0.0,0.0
2026-04-23 00:00:00-04:00,419.890015,423.660004,411.410004,415.750000,38308000,0.0,0.0
2026-04-24 00:00:00-04:00,416.970001,424.950012,415.799988,424.619995,27457400,0.0,0.0
2026-04-27 00:00:00-04:00,422.380005,427.109985,417.070007,424.820007,30867300,0.0,0.0
2026-04-28 00:00:00-04:00,424.570007,429.920013,421.899994,429.250000,30438100,0.0,0.0
2026-04-29 00:00:00-04:00,424.579987,426.820007,420.290009,424.459991,38288300,0.0,0.0
2026-04-30 00:00:00-04:00,410.809998,414.420013,398.010010,407.779999,70909400,0.0,0.0
2026-05-01 00:00:00-04:00,412.799988,417.109985,410.440002,414.440002,31372400,0.0,0.0
2026-05-04 00:00:00-04:00,411.540009,420.779999,410.799988,413.619995,28066500,0.0,0.0
2026-05-05 00:00:00-04:00,415.320007,416.779999,408.799988,411.380005,25700900,0.0,0.0
2026-05-06 00:00:00-04:00,408.000000,418.420013,405.109985,413.959991,30285900,0.0,0.0
2026-05-07 00:00:00-04:00,420.109985,427.980011,418.760010,420.769989,34942400,0.0,0.0
2026-05-08 00:00:00-04:00,417.390015,418.630005,414.000000,415.119995,33383800,0.0,0.0
2026-05-11 00:00:00-04:00,407.774994,412.690002,405.500000,412.660004,34355600,0.0,0.0

In [6]:
data.option_chain(data.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT260513C00350000,2026-05-11 17:42:55+00:00,350.0,60.29,60.60,63.15,-1.049999,-1.711769,34.0,360,1.233402,True,REGULAR,USD
1,MSFT260513C00352500,2026-05-11 15:39:43+00:00,352.5,58.40,58.10,60.65,-0.469997,-0.798365,4.0,10,1.188481,True,REGULAR,USD
2,MSFT260513C00355000,2026-04-30 13:58:46+00:00,355.0,51.85,55.65,58.30,0.000000,0.000000,NaN,311,1.203617,True,REGULAR,USD
3,MSFT260513C00357500,2026-04-29 19:15:01+00:00,357.5,68.75,53.10,55.65,0.000000,0.000000,NaN,47,1.099614,True,REGULAR,USD
4,MSFT260513C00360000,2026-04-29 13:37:49+00:00,360.0,64.35,50.65,53.25,0.000000,0.000000,NaN,208,1.093755,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,MSFT260513C00515000,2026-05-08 13:48:17+00:00,515.0,0.03,0.00,0.01,-0.090000,-75.000000,2.0,10,0.921876,False,REGULAR,USD
66,MSFT260513C00517500,2026-05-07 14:26:19+00:00,517.5,0.16,0.00,0.01,0.000000,0.000000,1.0,7,0.937501,False,REGULAR,USD
67,MSFT260513C00520000,2026-05-06 17:17:07+00:00,520.0,0.03,0.00,0.01,0.000000,0.000000,6.0,7,0.968750,False,REGULAR,USD
68,MSFT260513C00522500,2026-04-30 14:20:38+00:00,522.5,0.15,0.00,0.01,0.000000,0.000000,NaN,1,0.968750,False,REGULAR,USD
69,MSFT260513C00525000,2026-05-01 14:42:06+00:00,525.0,0.23,0.00,0.01,0.000000,0.000000,1.0,3,0.984375,False,REGULAR,USD

In [7]:
data.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         11   41     3     0           0
1    -1m          9   42     3     0           0
2    -2m         10   45     3     0           0
3    -3m         10   44     3     0           0

In [8]:
data.upgrades_downgrades

,Firm,ToGrade,FromGrade,Action,priceTargetAction,currentPriceTarget,priorPriceTarget
GradeDate,,,,,,,
2026-05-06 22:53:27,Tigress Financial,Buy,Buy,main,Raises,680.0,595.0
2026-05-01 17:55:26,Stifel,Hold,Hold,main,Raises,415.0,392.0
2026-04-30 18:37:18,Bernstein,Outperform,Outperform,main,Raises,646.0,641.0
2026-04-30 18:08:38,Citigroup,Buy,Buy,main,Raises,620.0,600.0
2026-04-30 15:54:53,Evercore ISI Group,Outperform,Outperform,main,Lowers,510.0,580.0
...,...,...,...,...,...,...,...
2012-04-20 10:18:00,Deutsche Bank,Buy,,main,Raises,35.0,31.0
2012-04-03 15:53:00,UBS,Buy,,main,Raises,35.0,33.0
2012-03-22 11:03:00,Morgan Stanley,Overweight,,main,Raises,37.0,33.0
2012-03-19 18:00:00,Hilliard Lyons,Long-Term Buy,,main,Raises,37.0,0.0
2012-03-16 12:19:00,Argus Research,Buy,Hold,up,Announces,0.0,0.0

In [9]:
data.sustainability

HTTP Error 404:

Empty DataFrame
Columns: []
Index: []

In [10]:
data.analyst_price_targets

{'current': 412.66,
 'high': 870.0,
 'low': 400.0,
 'mean': 561.5561,
 'median': 562.5}

In [11]:
data.earnings_estimate

             avg       low   high  yearAgoEps  numberOfAnalysts  growth
period
0q       4.24777   4.07000   4.89     3.65000                31  0.1638
+1q      4.62403   4.38000   4.98     4.13000                28  0.1196
0y      16.85079  16.69775  17.63    13.64000                24  0.2354
+1y     19.35454  18.12644  20.57    16.85079                37  0.1486

In [12]:
data.revenue_estimate

,avg,low,high,numberOfAnalysts,yearAgoRevenue,growth
period,,,,,,
0q,87610832320,86900000000,91239000000,39,76441000000,0.1461
+1q,89665223660,87795000000,91451000000,34,77673000000,0.1544
0y,329462095550,327235000000,333071000000,48,281724000000,0.1694
+1y,383929215340,369086000000,406233368370,53,329462095550,0.1653

In [13]:
data.earnings_history

            epsActual  epsEstimate  epsDifference  surprisePercent
quarter
2025-06-30       3.65      3.37669           0.27           0.0809
2025-09-30       4.13      3.66355           0.47           0.1273
2025-12-31       4.14      3.91702           0.22           0.0569
2026-03-31       4.27      4.05827           0.21           0.0522

In [14]:
data.eps_trend

         current  7daysAgo  30daysAgo  60daysAgo  90daysAgo
period
0q       4.24777   4.24283    4.25802    4.26044    4.26147
+1q      4.62403   4.55178    4.56609    4.56939    4.57189
0y      16.85079  16.80082   16.64591   16.65616   16.64616
+1y     19.35454  19.31938   18.83292   18.82898   18.83504

In [15]:
data.eps_revisions

        upLast7days  upLast30days  downLast30days  downLast7Days
period
0q               10             6              16             17
+1q              10            11               7              7
0y               19            20               1              0
+1y              19            18               9              9

In [16]:
data.growth_estimates

        stockTrend  indexTrend
period
0q          0.1638      0.2482
+1q         0.1196      0.2073
0y          0.2354      0.2188
+1y         0.1486      0.1520
LTG            NaN      0.1220

In [17]:
data.funds_data

In [18]:
data.insider_purchases

       Insider Purchases Last 6m     Shares  Trans
0                      Purchases    17532.0     13
1                          Sales    31762.0      4
2    Net Shares Purchased (Sold)   -14230.0     17
3      Total Insider Shares Held  6685592.0   <NA>
4  % Net Shares Purchased (Sold)     -0.002   <NA>
5                   % Buy Shares      0.003   <NA>
6                  % Sell Shares      0.005   <NA>

In [19]:
data.insider_transactions

,Shares,Value,URL,Text,Insider,Position,Transaction,Start Date,Ownership
0,12320,5045643,,Sale at price 409.52 per share.,HOGAN KATHLEEN T,Officer,,2026-03-06,D
1,5000,1986750,,Purchase at price 397.35 per share.,STANTON JOHN W.,Director,,2026-02-18,D
2,145,0,,Stock Award(Grant) at price 0.00 per share.,LIST TERI,Director,,2026-01-30,D
3,145,0,,Stock Award(Grant) at price 0.00 per share.,MASON MARK A.L.,Director,,2026-01-30,D
4,145,0,,Stock Award(Grant) at price 0.00 per share.,STANTON JOHN W.,Director,,2026-01-30,D
...,...,...,...,...,...,...,...,...,...
94,138,0,,Stock Award(Grant) at price 0.00 per share.,STANTON JOHN W.,Director,,2024-06-07,D
95,138,0,,Stock Award(Grant) at price 0.00 per share.,SCHARF CHARLES W,Director,,2024-06-07,D
96,16996,0,,Stock Gift at price 0.00 per share.,NADELLA SATYA,Chief Executive Officer,,2024-06-05,I
97,566,235535,,Sale at price 415.53 - 416.60 per share.,NUMOTO TAKESHI,Officer,,2024-06-03,D
98,25000,10641950,,Sale at price 425.68 per share.,ALTHOFF JUDSON,Officer,,2024-05-23,D

In [20]:
data.insider_roster_holders

,Name,Position,URL,Most Recent Transaction,Latest Transaction Date,Shares Owned Directly,Position Direct Date
0,ALTHOFF JUDSON,Officer,,Sale,2025-12-02,129349,2025-12-02
1,COLEMAN AMY,Officer,,Stock Award(Grant),2025-09-15,45923,2025-09-15
2,HOGAN KATHLEEN T,Officer,,Sale,2026-03-06,137933,2026-03-06
3,HOOD AMY E,Chief Financial Officer,,Stock Award(Grant),2025-09-15,567567,2025-09-15
4,JOLLA ALICE L,Officer,,Stock Award(Grant),2025-08-29,73016,2025-08-29
5,NADELLA SATYA,Chief Executive Officer,,Stock Gift,2025-11-10,896595,2025-11-10
6,NUMOTO TAKESHI,Officer,,Sale,2025-12-04,55781,2025-12-04
7,SMITH BRADFORD LEE,President,,Stock Gift,2025-11-06,451597,2025-11-06
8,STANTON JOHN W.,Director,,Purchase,2026-02-18,87527,2026-02-18
9,YOUNG CHRISTOPHER DAVID,Officer,,Sale,2024-11-12,104866,2024-11-12

In [21]:
data.major_holders

Breakdown                          Value
insidersPercentHeld              0.00090
institutionsPercentHeld          0.78339
institutionsFloatPercentHeld     0.78410
institutionsCount             8037.00000

In [22]:
data.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value,pctChange
0,2025-12-31,Blackrock Inc.,0.0810,601897495,248379022490,0.0170
1,2026-03-31,Vanguard Capital Management LLC,0.0650,482558086,199132421535,1.0000
2,2025-12-31,State Street Corporation,0.0412,306150608,126336111018,0.0213
3,2025-12-31,"FMR, LLC",0.0271,200948745,82923509847,-0.0453
4,2025-12-31,"Geode Capital Management, LLC",0.0246,182618400,75359309612,0.0106
5,2026-03-31,Vanguard Portfolio Management LLC,0.0225,167490848,69116773949,1.0000
6,2025-12-31,JPMORGAN CHASE & CO,0.0199,147759850,60974580242,-0.5348
7,2025-12-31,Price (T.Rowe) Associates Inc,0.0169,125709121,51875126332,-0.0489
8,2025-12-31,Morgan Stanley,0.0163,121220561,50022877146,0.0082
9,2025-12-31,NORGES BANK,0.0141,104761241,43230774094,0.0320

In [23]:
data.mutualfund_holders

,Date Reported,Holder,pctHeld,Shares,Value,pctChange
0,2025-12-31,VANGUARD INDEX FUNDS-Vanguard Total Stock Mark...,0.0314,233573777,96386555672,-0.0017
1,2025-12-31,VANGUARD INDEX FUNDS-Vanguard 500 Index Fund,0.0252,187420611,77340990021,0.0219
2,2026-03-31,iShares Trust-iShares Core S&P 500 ETF,0.0128,95450669,39388673419,0.0074
3,2026-03-31,Fidelity Concord Street Trust-Fidelity 500 Ind...,0.0128,94830980,39132952554,0.0026
4,2026-03-31,SPDR S&P 500 ETF TRUST-State Street SPDR S&P 5...,0.0116,86106881,35532865828,-0.0154
5,2025-12-31,VANGUARD INDEX FUNDS-Vanguard Growth Index Fund,0.0104,77560271,32006021714,0.0959
6,2026-04-30,"Invesco QQQ Trust, Series 1",0.0078,57570410,23757005601,0.0160
7,2025-12-31,VANGUARD INSTITUTIONAL INDEX FUNDS-Vanguard In...,0.0057,42653431,17601364992,-0.0156
8,2026-02-28,VANGUARD WORLD FUND-Vanguard Information Techn...,0.0045,33783805,13941225095,0.0252
9,2026-03-31,GROWTH FUND OF AMERICA,0.0045,33502584,13825176436,-0.0056

In [ ]:
try:
    from .edgar_wrapper import Company, set_identity, MultiFinancials  # type: ignore
except ImportError:
    from edgar_wrapper import Company, set_identity, MultiFinancials  # type: ignore

identity = f"Alphalistar Limited alphalistai@gmail.com"
set_identity(identity)
symbol = 'GOOGL'
company = Company(symbol)

# latest_10Qs = company.get_filings(form="10-Q")

filings = company.get_filings(form="10-Q")

filing = filings[0]
attachment = filing.attachments[10]

# dir(attachment)

attachment.view()

# content = filing.markdown()
# print(content)

SyntaxError: positional argument follows keyword argument (1417586588.py, line 13)